# -*- coding: utf-8 -*-
{
    'name': 'DJBC Pemasukan Hasil Produksi (KITE)',
    'version': '12.0.1.0.0',
    'summary': ' ',
    'description': ' ',
    'category': 'Extra Tools',
    'author': 'Geger ',
    'website': '-',
    # 'license': 'AGPL',
    'depends': ['djbc'],
    'data': [
        'security/ir.model.access.csv',
        'wizards/kite_php_wiz.xml',
        'wizards/kite_pw_wiz.xml', 
        'views/kite_php.xml',
        'views/kite_pw.xml',
        'views/menu.xml',
        'wizards/kite_pbb_wiz.xml', 
        'views/kite_pbb.xml',
        'wizards/kite_pembb_wiz.xml', 
        'views/kite_pembb.xml',
        'wizards/kite_pemws_wiz.xml', 
        'views/kite_pemws.xml',
        'wizards/kite_penghp_wiz.xml', 
        'views/kite_penghp.xml',
        'wizards/kite_mbb_wiz.xml', 
        'views/kite_mbb.xml',
        'wizards/kite_mhp_wiz.xml', 
        'views/kite_mhp.xml',
    ],
    'demo': [''],
    'installable': True,
    'auto_install': False,
    # 'external_dependencies': {
    #    'python': [''],
    # }
}
